#!/usr/bin/env python3
from pathlib import Path
import sys

P = Path(sys.argv[1]).resolve()
K = P / "app/src/main/java/com/localqbank/library"
gradle = P / "app/build.gradle.kts"
home = K / "RovexHomeRevolution.kt"
test = P / "app/src/androidTest/java/com/localqbank/library/RovexFlowSurfaceRegressionTest.kt"
if not gradle.is_file() or not home.is_file() or not test.is_file():
    raise SystemExit("[644] required source/test missing")
g = gradle.read_text()
if 'versionName = "8.3.643"' not in g or "versionCode = 729" not in g:
    raise SystemExit("[644] wrong baseline; expected v8.3.643 / versionCode 729")
gradle.write_text(g.replace('versionName = "8.3.643"', 'versionName = "8.3.644"', 1).replace("versionCode = 729", "versionCode = 730", 1))

# Existing explicit surfaces are not equivalent to heuristic auto-wrappers. Phase 643's
# test incorrectly rejected all motion wrappers, so it failed on five intentional pre-existing
# tags even though the automatic scanner was disabled. Assert only the regression being fixed.
test.write_text("""package com.localqbank.library

import android.content.Intent
import android.view.View
import android.view.ViewGroup
import androidx.test.core.app.ActivityScenario
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class RovexFlowSurfaceRegressionTest {
    @Test
    fun homeLayoutDoesNotContainHeuristicAutoGeneratedMotionWrappers() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        ActivityScenario.launch<MainActivity>(Intent(context, MainActivity::class.java)).use { scenario ->
            scenario.onActivity { activity ->
                val root = activity.findViewById<ViewGroup>(R.id.dashboardRoot)
                    ?: error("Home dashboard root missing")
                val autoWrappers = mutableListOf<String>()
                fun walk(view: View) {
                    val tag = view.tag?.toString().orEmpty()
                    if (tag.startsWith("rovex_motion_surface:auto-")) autoWrappers.add(tag)
                    if (view is ViewGroup) for (i in 0 until view.childCount) walk(view.getChildAt(i))
                }
                walk(root)
                check(autoWrappers.isEmpty()) {
                    "Heuristic auto-generated Home wrappers must be disabled; found " + autoWrappers
                }
            }
        }
    }
}
""")
if "startsWith(\"rovex_motion_surface:auto-\")" not in test.read_text():
    raise SystemExit("[644] auto-wrapper-only test contract missing")
if "No heuristic view reparenting on Home." not in home.read_text():
    raise SystemExit("[644] Home auto-reparenting remains enabled")
print("[644] applied v8.3.644 / versionCode 730")
print("[644] fixed false-positive regression test: rejects only heuristic auto-generated wrappers, not five intentional surfaces")
