#!/usr/bin/env python3
from pathlib import Path
import hashlib
import json
import sys

PROJECT = Path(sys.argv[1]).resolve()
PKG = PROJECT / "app/src/main/java/com/localqbank/library"
ASSET = PROJECT / "app/src/main/assets/rovex/motion/gradient_animated_background.json"
MANIFEST = PROJECT / "app/src/main/assets/rovex/RovexVisualAssetManifest.json"

def source(name):
    p = PKG / name
    if not p.is_file():
        raise SystemExit(f"[637] missing expected source: {p}")
    return p

gradle = PROJECT / "app/build.gradle.kts"
g = gradle.read_text()
if 'versionName = "8.3.636"' not in g or "versionCode = 722" not in g:
    raise SystemExit("[637] expected v8.3.636 / 722 baseline; refusing to patch")
gradle.write_text(g.replace('versionName = "8.3.636"', 'versionName = "8.3.637"', 1).replace("versionCode = 722", "versionCode = 723", 1))

# Imported third-party animation; never synthesized or generated by this build.
ASSET_JSON = r'''{"v":"4.6.10","fr":15,"ip":0,"op":155,"w":1080,"h":1920,"nm":"background","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 1","ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[540,960,0]},"a":{"a":0,"k":[0,0,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[1160,880]},"p":{"a":0,"k":[0,0]},"r":{"a":0,"k":0},"nm":"Rectangle Path 1","mn":"ADBE Vector Shape - Rect"},{"ty":"st","c":{"a":0,"k":[0.9960784,0.7843137,0.145098,1]},"o":{"a":0,"k":100},"w":{"a":0,"k":6},"lc":1,"lj":1,"ml":4,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke"},{"ty":"gf","o":{"a":0,"k":100},"r":1,"g":{"p":3,"k":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[0,0.511,0.89,0.283,0.5,0.334,0.873,0.583,1,0.156,0.857,0.882],"e":[0,0.726,0.283,0.89,0.5,0.441,0.356,0.886,1,0.156,0.429,0.882]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":31,"s":[0,0.726,0.283,0.89,0.5,0.441,0.356,0.886,1,0.156,0.429,0.882],"e":[0,0.89,0.283,0.283,0.5,0.886,0.553,0.219,1,0.882,0.823,0.156]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":61,"s":[0,0.89,0.283,0.283,0.5,0.886,0.553,0.219,1,0.882,0.823,0.156],"e":[0,0,0.312,0.737,0.5,0.078,0.597,0.754,1,0.156,0.882,0.771]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":91,"s":[0,0,0.312,0.737,0.5,0.078,0.597,0.754,1,0.156,0.882,0.771],"e":[0,0.51,0.89,0.282,0.5,0.333,0.873,0.582,1,0.157,0.855,0.882]},{"t":120}]}},"s":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[-430.769,-404.573],"e":[23.726,-364.48],"to":[75.7491683959961,6.68213844299316],"ti":[-123.915840148926,-8.51547145843506]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":31,"s":[23.726,-364.48],"e":[312.726,-353.48],"to":[123.915840148926,8.51547145843506],"ti":[-1.00208830833435,-1.83333337306976]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":61,"s":[312.726,-353.48],"e":[29.739,-353.48],"to":[1.00208830833435,1.83333337306976],"ti":[120.055290222168,0.60746711492538]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":91,"s":[29.739,-353.48],"e":[-407.606,-357.125],"to":[-120.055290222168,-0.60746711492538],"ti":[72.8907089233398,0.60746711492538]},{"t":120}]},"e":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[374.412,342.611],"e":[22.822,357.191],"to":[-58.5984153747559,2.42986845970154],"ti":[132.520950317383,-7.89707231521606]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":31,"s":[22.822,357.191],"e":[-420.714,389.994],"to":[-132.520950317383,7.89707231521606],"ti":[-4.68509674072266,-7.89707231521606]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":61,"s":[-420.714,389.994],"e":[50.932,404.573],"to":[4.68509674072266,7.89707231521606],"ti":[-132.918350219727,4.25226974487305]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":91,"s":[50.932,404.573],"e":[376.797,364.48],"to":[132.918350219727,-4.25226974487305],"ti":[-54.3107261657715,6.68213844299316]},{"t":120}]},"t":1,"nm":"Gradient Fill 1","mn":"ADBE Vector Graphic - G-Fill"},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[93.29,219.491],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Rectangle 1","np":3,"cix":2,"ix":1,"mn":"ADBE Vector Group"}],"ip":0,"op":155,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":2,"ty":1,"nm":"Deep Red Solid 1","ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[540,960,0]},"a":{"a":0,"k":[540,960,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"sw":1080,"sh":1920,"sc":"#be2a2a","ip":0,"op":155,"st":0,"bm":0,"sr":1}]}'''
asset_data = ASSET_JSON.strip() + "\n"
ASSET.parent.mkdir(parents=True, exist_ok=True)
ASSET.write_text(asset_data)
asset_sha = hashlib.sha256(asset_data.encode("utf-8")).hexdigest()

license_note = """Rovex third-party motion assets

Gradient Animated Background
- Creator/source page: https://lottiefiles.com/free-animation/gradient-animated-background-Gyh6Lr3KGK
- Imported JSON mirror: https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/lottiefiles/gradient_animated_background.json
- License: Lottie Simple License (the LottieFiles page marks this animation free to use under that license).
- The animation is bundled as part of Rovex's UI, not offered as a standalone downloadable asset.
- This is a free-use licensed asset, not public-domain/CC0. Preserve this notice and re-check the upstream license if the asset is replaced.

Existing Rovex assets remain listed in RovexVisualAssetManifest.json.
"""
(PROJECT / "app/src/main/assets/rovex/motion/THIRD_PARTY_ASSETS.md").write_text(license_note)

manifest = json.loads(MANIFEST.read_text())
manifest["generatedBy"] = "Rovex 8.3.637 external motion asset pipeline"
assets = manifest.setdefault("assets", [])
entry = {
    "file": "assets/rovex/motion/gradient_animated_background.json",
    "type": "lottie-json",
    "source": "https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/lottiefiles/gradient_animated_background.json",
    "sourcePage": "https://lottiefiles.com/free-animation/gradient-animated-background-Gyh6Lr3KGK",
    "creator": "LottieFiles community",
    "license": "Lottie Simple License",
    "sha256": asset_sha,
    "modified": False
}
assets[:] = [item for item in assets if item.get("file") != entry["file"]]
assets.append(entry)
MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")

p = source("RovexHomeRevolution.kt")
s = p.read_text()
anchor = '    private fun d(v:Int,c:Context)=(v*c.resources.displayMetrics.density).toInt()\n'
helpers = """    private const val MOTION_BG_TAG = "rovex_home_motion_background"
    private const val MOTION_CARD_PREFIX = "rovex_home_motion_card:"
    private var motionPolicyAllowed = true
    private fun motionAlpha(c:Context, background:Boolean):Float {
        val card = when (ThemeManager.get(c)) {
            ThemeManager.LIGHT -> 0.22f
            ThemeManager.PASTEL -> 0.20f
            ThemeManager.MINT -> 0.18f
            ThemeManager.SUNSET -> 0.20f
            ThemeManager.LAVENDER -> 0.20f
            ThemeManager.AMOLED -> 0.12f
            ThemeManager.PANDORA -> 0.14f
            ThemeManager.SPACE -> 0.12f
            else -> 0.16f
        }
        return if (background) card * 0.42f else card
    }

    private fun motionBackground(c:Context, tagValue:String, background:Boolean=false):LottieAnimationView? {
        if (!motionPolicyAllowed) return null
        val view = LottieAnimationView(c).apply {
            tag = tagValue
            setAnimation("rovex/motion/gradient_animated_background.json")
            repeatCount = LottieDrawable.INFINITE
            repeatMode = LottieDrawable.RESTART
            speed = 0.38f
            alpha = motionAlpha(c, background)
            scaleType = ImageView.ScaleType.CENTER_CROP
            renderMode = RenderMode.HARDWARE
            isClickable = false
            isFocusable = false
            importantForAccessibility = View.IMPORTANT_FOR_ACCESSIBILITY_NO
            contentDescription = null
        }
        view.addOnAttachStateChangeListener(object : View.OnAttachStateChangeListener {
            override fun onViewAttachedToWindow(v:View) {
                v.post { updateMotionView(view, c) }
            }
            override fun onViewDetachedFromWindow(v:View) {
                runCatching { view.cancelAnimation() }
            }
        })
        return view
    }

    private fun updateMotionView(view:LottieAnimationView, c:Context, forcePause:Boolean=false) {
        val tag = view.tag as? String ?: return
        if (tag != MOTION_BG_TAG && !tag.startsWith(MOTION_CARD_PREFIX)) return
        view.alpha = motionAlpha(c, tag == MOTION_BG_TAG)
        val visibleRect = android.graphics.Rect()
        val visible = !forcePause && view.isShown &&
            view.getGlobalVisibleRect(visibleRect) && visibleRect.width() > 0 && visibleRect.height() > 0
        if (visible && motionPolicyAllowed) runCatching { view.resumeAnimation() }
        else runCatching { view.pauseAnimation() }
    }

    private fun updateMotionTree(view:View, c:Context, forcePause:Boolean=false) {
        if (view is LottieAnimationView) updateMotionView(view, c, forcePause)
        if (view is ViewGroup) for (i in 0 until view.childCount) updateMotionTree(view.getChildAt(i), c, forcePause)
    }

    fun pauseMotion(a:MainActivity) {
        val root = a.findViewById<ViewGroup>(R.id.dashboardRoot) ?: return
        root.findViewWithTag<FrameLayout>(TAG)?.let { updateMotionTree(it, a, true) }
    }

"""
if anchor not in s: raise SystemExit("[637] Home helper insertion anchor missing")
s = s.replace(anchor, anchor + helpers, 1)

old_refresh = '''        root.findViewWithTag<FrameLayout>(TAG)?.let{it.background=if (ThemeManager.get(a) == ThemeManager.LIGHT) RovexClinicalDayHomeBackgroundDrawable(a) else ThemeManager.backgroundDrawable(a);it.invalidate()}'''
new_refresh = '''        motionPolicyAllowed = AnimationPolicy.enabled(a)
        root.findViewWithTag<FrameLayout>(TAG)?.let {
            it.background = if (ThemeManager.get(a) == ThemeManager.LIGHT) RovexClinicalDayHomeBackgroundDrawable(a) else ThemeManager.backgroundDrawable(a)
            updateMotionTree(it, a)
            it.invalidate()
        }'''
if old_refresh not in s: raise SystemExit("[637] refreshTheme anchor missing")
s = s.replace(old_refresh, new_refresh, 1)

old_box = '''        val box=FrameLayout(a).apply{background=card(a,index);setPadding(d(14,a),d(13,a),d(10,a),d(10,a));isClickable=true;isFocusable=true;elevation=d(4,a).toFloat();setOnClickListener{target()}}
        val col=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL}'''
new_box = '''        val box=FrameLayout(a).apply{background=card(a,index);setPadding(d(14,a),d(13,a),d(10,a),d(10,a));isClickable=true;isFocusable=true;elevation=d(4,a).toFloat();setOnClickListener{target()}}
        motionBackground(a, MOTION_CARD_PREFIX + title)?.let { motion ->
            val clip = FrameLayout(a).apply {
                background = GradientDrawable().apply { cornerRadius = d(22,a).toFloat(); setColor(Color.TRANSPARENT) }
                clipToOutline = true
                importantForAccessibility = View.IMPORTANT_FOR_ACCESSIBILITY_NO
            }
            clip.addView(motion, FrameLayout.LayoutParams(-1,-1))
            box.addView(clip, FrameLayout.LayoutParams(-1,-1).apply {
                leftMargin = -d(14,a); topMargin = -d(13,a); rightMargin = -d(10,a); bottomMargin = -d(10,a)
            })
        }
        val col=LinearLayout(a).apply{orientation=LinearLayout.VERTICAL}'''
if old_box not in s: raise SystemExit("[637] feature card insertion anchor missing")
s = s.replace(old_box, new_box, 1)

old_shell = '''        val shell=FrameLayout(a).apply{tag=TAG;contentDescription="rovexHomeShell";background=if (ThemeManager.get(a) == ThemeManager.LIGHT) RovexClinicalDayHomeBackgroundDrawable(a) else ThemeManager.backgroundDrawable(a)}
        val scroll=ScrollView(a).apply{tag="ROVEX_HOME_SCROLL";overScrollMode=View.OVER_SCROLL_NEVER;clipToPadding=false;isFillViewport=true}'''
new_shell = '''        motionPolicyAllowed = AnimationPolicy.enabled(a)
        val shell=FrameLayout(a).apply{tag=TAG;contentDescription="rovexHomeShell";background=if (ThemeManager.get(a) == ThemeManager.LIGHT) RovexClinicalDayHomeBackgroundDrawable(a) else ThemeManager.backgroundDrawable(a)}
        motionBackground(a, MOTION_BG_TAG, true)?.let { shell.addView(it, FrameLayout.LayoutParams(-1,-1)) }
        val scroll=ScrollView(a).apply{tag="ROVEX_HOME_SCROLL";overScrollMode=View.OVER_SCROLL_NEVER;clipToPadding=false;isFillViewport=true}
        scroll.setOnScrollChangeListener { _, _, _, _, _ -> updateMotionTree(shell, a) }'''
if old_shell not in s: raise SystemExit("[637] Home shell insertion anchor missing")
s = s.replace(old_shell, new_shell, 1)

root_anchor = '        root.addView(shell,ViewGroup.LayoutParams(-1,-1))\n'
if root_anchor not in s: raise SystemExit("[637] root attach anchor missing")
s = s.replace(root_anchor, root_anchor + '        shell.post { updateMotionTree(shell, a) }\n', 1)
p.write_text(s)

m = source("MainActivity.kt")
ms = m.read_text()
old_pause = '    override fun onPause(){ super.onPause() }'
new_pause = '    override fun onPause(){ RovexHomeRevolution.pauseMotion(this); super.onPause() }'
if old_pause not in ms: raise SystemExit("[637] MainActivity onPause anchor missing")
ms = ms.replace(old_pause, new_pause, 1)
m.write_text(ms)

# Structural postconditions catch a silent/partial overlay before the build starts.
home = (PKG / "RovexHomeRevolution.kt").read_text()
main = (PKG / "MainActivity.kt").read_text()
if "gradient_animated_background.json" not in home or "updateMotionTree(shell, a)" not in home:
    raise SystemExit("[637] imported Lottie background/card motion was not wired")
if "RovexHomeRevolution.pauseMotion(this)" not in main:
    raise SystemExit("[637] Home motion lifecycle pause was not wired")
if "gradient_animated_background.json" not in MANIFEST.read_text():
    raise SystemExit("[637] external motion asset is missing from the manifest")

print("[637] applied v8.3.637 / versionCode 723")
print(f"[637] imported Lottie background JSON ({len(asset_data.encode('utf-8'))} bytes, sha256={asset_sha}) with explicit license/source record")
print("[637] Home gradient motion is theme-alpha-adaptive, clipped to feature cards, paused when offscreen/detached or Activity pauses, and respects AnimationPolicy")
